### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/var/run/dionaeafr/dionaeafr.pid'

### ISSUE THREAD

**Issue by jannae** [rubenespadas/DionaeaFR#22]
Running `python manage.py collectstatic` produces this error.

Has a step been missed somewhere in the instructions?

**Comment by Waseem-farooqui** [comment]
I was having the same issue, I resolved it by adding this code in **manage.py**

    #!/usr/bin/env python
    import os, sys

    if __name__ == "__main__":
        os.environ.setdefault("DJANGO_SETTINGS_MODULE", "DionaeaFR.settings")
         from django.core.management import execute_from_command_line
         execute_from_command_line(sys.argv)
If you face this error while accessing its interface

     Error: Cannot find module 'promise'
        at Function.Module._resolveFilename (module.js:338:15)
This might be because of older version of `Node.js` or you were probably already alerted of this issue when you installed npm install -g less.
so update by first checking the latest http://nodejs.org/download/
in my case it was v0.12.0
so 
1      cd /opt/
2	wget http://nodejs.org/dist/v0.12.0/node-v0.12.0.tar.gz
3	tar xzvf node-v0.12.0.tar.gz
4	cd node-v0.12.0
5	./configure
6	make
7	make install
now run it, It will work fine.

**Comment by jinverar** [comment]
I am seeing the same issue in 2015. I have tried multiple ver. of nodejs and modifying the manage.py file see output below.
root@ghosthp-500-439:/opt/DionaeaFR# python manage.py collectstatic
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    file(pidfile, 'w').write(pid)
IOError: [Errno 2] No such file or directory: '/var/run/dionaeafr/dionaeafr.pid'
root@ghosthp-500-439:/opt/DionaeaFR# python manage.py runserver 0.0.0.0:8000
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    file(pidfile, 'w').write(pid)
IOError: [Errno 2] No such file or directory: '/var/run/dionaeafr/dionaeafr.pid'

**Comment by Waseem-farooqui** [comment]
You need to change `manage.py` by this
        
 #!/usr/bin/env python
 import os, sys
    if __name__ == "__main__":
        os.environ.setdefault("DJANGO_SETTINGS_MODULE", "DionaeaFR.settings")
         from django.core.management import execute_from_command_line
         execute_from_command_line(sys.argv)

It works in my case.

**Comment by rosidermawati** [comment]
> You need to change `manage.py` by this
> 
> #!/usr/bin/env python
> import os, sys
> if **name** == "**main**":
> os.environ.setdefault("DJANGO_SETTINGS_MODULE", "DionaeaFR.settings")
> from django.core.management import execute_from_command_line
> execute_from_command_line(sys.argv)
> 
> It works in my case.

hello ..
I'm trying to run dionaeaFR web server with the command python manage.py collectstatic. I get an error
Traceback (most recent call last):
File "manage.py", line 14, in
file (pidfile, 'w'). write (pid)
IOError: [Errno 2] No such file or directory: '/var/run/dionaeafr/dionaeafr.pid'
Can you help me ? please
