### ISSUE TITLE
Error loading the web: ImportError: No module named django_filters

### ISSUE THREAD

**Issue by xmlx** [rubenespadas/DionaeaFR#24]
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/DionaeaFR/DionaeaFR/urls.py", line 4, in <module>
    from Web.views.connection import connectionIndex, connectionDetail
  File "/opt/DionaeaFR/Web/views/connection.py", line 22, in <module>
    from Web.filters.connection import ConnectionFilter
  File "/opt/DionaeaFR/Web/filters/connection.py", line 1, in <module>
    import django_filters as filters
ImportError: No module named django_filters
[17/Apr/2015 03:31:17]"GET / HTTP/1.1" 500 14743
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/DionaeaFR/DionaeaFR/urls.py", line 4, in <module>
    from Web.views.connection import connectionIndex, connectionDetail
  File "/opt/DionaeaFR/Web/views/connection.py", line 22, in <module>
    from Web.filters.connection import ConnectionFilter
  File "/opt/DionaeaFR/Web/filters/connection.py", line 1, in <module>
    import django_filters as filters
ImportError: No module named django_filters

Please Help.

**Comment by rubenespadas** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

pip install django-filter

El 17/04/2015 a las 5:56, xmlx escribió:
> Internal Server Error: / Traceback (most recent call last): File 
> "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py",
>
> 
line 119, in get_response resolver_match =
> resolver.resolve(request.path_info) File 
> "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py",
>
> 
line 366, in resolve for pattern in self.url_patterns: File
> "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py",
>
> 
line 402, in url_patterns patterns = getattr(self.urlconf_module,
> "urlpatterns", self.urlconf_module) File 
> "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py",
>
> 
line 396, in urlconf_module self._urlconf_module =
> import_module(self.urlconf_name) File 
> "/usr/lib/python2.7/importlib/__init__.py", line 37, in 
> import_module __import__(name) File 
> "/opt/DionaeaFR/DionaeaFR/urls.py", line 4, in <module> from 
> Web.views.connection import connectionIndex, connectionDetail File 
> "/opt/DionaeaFR/Web/views/connection.py", line 22, in <module>
> from Web.filters.connection import ConnectionFilter File 
> "/opt/DionaeaFR/Web/filters/connection.py", line 1, in <module> 
> import django_filters as filters ImportError: No module named 
> django_filters [17/Apr/2015 03:31:17]"GET / HTTP/1.1" 500 14743 
> Internal Server Error: /favicon.ico Traceback (most recent call 
> last): File 
> "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py",
>
> 
line 108, in get_response response = middleware_method(request)
> File 
> "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py",
>
> 
line 74, in process_request if (not
> urlresolvers.is_valid_path(request.path_info, urlconf) and File 
> "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py",
>
> 
line 647, in is_valid_path resolve(path, urlconf) File
> "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py",
>
> 
line 522, in resolve return get_resolver(urlconf).resolve(path)
> File 
> "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py",
>
> 
line 366, in resolve for pattern in self.url_patterns: File
> "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py",
>
> 
line 402, in url_patterns patterns = getattr(self.urlconf_module,
> "urlpatterns", self.urlconf_module) File 
> "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py",
>
> 
line 396, in urlconf_module self._urlconf_module =
> import_module(self.urlconf_name) File 
> "/usr/lib/python2.7/importlib/__init__.py", line 37, in 
> import_module __import__(name) File 
> "/opt/DionaeaFR/DionaeaFR/urls.py", line 4, in <module> from 
> Web.views.connection import connectionIndex, connectionDetail File 
> "/opt/DionaeaFR/Web/views/connection.py", line 22, in <module>
> from Web.filters.connection import ConnectionFilter File 
> "/opt/DionaeaFR/Web/filters/connection.py", line 1, in <module> 
> import django_filters as filters ImportError: No module named 
> django_filters
> 
> 
> Please Help.
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/rubenespadas/DionaeaFR/issues/24
> 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBAgAGBQJVML2BAAoJEOy3CPZSmH0rTiEH/jIg4jGZ3EjFZpH7d8JssZrk
8zDM2I17pBBJ+ddRgQgtsPs7sYDjnTOxTaC50Xr86x6XBH8n4aaGjOl+/DRP3nlw
Bi3YTLqIaGoVtn3MKzEaj6I2+k5ov8k/8n8v7IwJkxFTRs/siCBiJPa3OugVbZZ1
MHdKa8YthRo1haMkcx2629aibvT+5hKm1Yoc2uBssneGUZLgDGvoGrnMnNJVMkC6
6O0InDYLh+nJ89J+jmaaYseao4rOpA1ecLpvRevuFQtncTtlxxjwfUoO8tebxKib
Opgw/PkFvhl9q39lLPVmjn2qZNzjL/QidYXc6ymLONtHO9leHHQmeuRTPrVXSwE=
=F/BC
-----END PGP SIGNATURE-----

**Comment by rubenespadas** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

pip install django-filter

El 17/04/2015 a las 5:56, xmlx escribió:

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBAgAGBQJVML18AAoJEOy3CPZSmH0r2bIIAIYV0P8WnY3O+ekzCtzCGDwq
S/FdvImJ1DXM2qTJQgpv+Q9qKKaBhxBNr692wNz/+dg6Mms5qmcu3YrmMwzzcCx0
5veyAOhkzKkP35hy0xz0/YeO7dHFMJMQ27VENvF41KTYnYvx8zpISOk1CE+gecO4
XOWsNHv2dwM8C6VicSiZLggIafx68EiRkkPTCOxAFLIeB5JGECDWJzm1xUxLHgwG
s6nws0NkK3mNwANiezBN54WDWVkb2fKOPN6v2Ccoe3dCtQMUdiX7zHZRe1A+uEDj
fwKsggFGuvxEphFVt7YuGHgZmielEquqOL7+LRF81S6B1e7LCmxYw717HoFczoo=
=3ykh
-----END PGP SIGNATURE-----
