### ISSUE TITLE
ImportError: No module named django

### ISSUE THREAD

**Issue by gregtampa** [rubenespadas/DionaeaFR#29]
root@sensor:/opt/DionaeaFR# /usr/local/bin/python2.7 manage.py runserver 0.0.0.0:8000
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
root@sensor:/opt/DionaeaFR# python2.7 -c "import django; print(django.get_version())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named django
root@sensor:/opt/DionaeaFR# pip freeze | grep -i django
Django==1.7
django-appconf==1.0.1
django-compressor==2.0
django-filter==0.13.0
django-htmlmin==0.9.0
django-pagination==1.0.7
django-tables2==1.1.2
django-tables2-simplefilter==0.1

**Comment by gregtampa** [comment]
from django.template.utils import InvalidTemplateEngineError
ImportError: No module named utils

**Comment by gregtampa** [comment]
sudo pip install Django-compressor==1.4
fixed it
