### ISSUE TITLE
ImportError: cannot import name ForeignObjectRel

### ISSUE THREAD

**Issue by gregtampa** [rubenespadas/DionaeaFR#30]
root@sensor:/opt/DionaeaFR# python manage.py runserver 0.0.0.0:8000
Validating models...

0 errors found
March 11, 2016 - 23:27:08
Django version 1.5, using settings 'DionaeaFR.settings'
Development server is running at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/DionaeaFR/DionaeaFR/urls.py", line 4, in <module>
    from Web.views.connection import connectionIndex, connectionDetail
  File "/opt/DionaeaFR/Web/views/connection.py", line 22, in <module>
    from Web.filters.connection import ConnectionFilter
  File "/opt/DionaeaFR/Web/filters/connection.py", line 1, in <module>
    import django_filters as filters
  File "/usr/local/lib/python2.7/dist-packages/django_filters/__init__.py", line 3, in <module>
    from .filterset import FilterSet
  File "/usr/local/lib/python2.7/dist-packages/django_filters/filterset.py", line 13, in <module>
    from django.db.models.fields.related import ForeignObjectRel
ImportError: cannot import name ForeignObjectRel
[11/Mar/2016 23:27:12] "GET / HTTP/1.1" 500 16280
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/common.py", line 69, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 551, in is_valid_path
    resolve(path, urlconf)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 440, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 319, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/DionaeaFR/DionaeaFR/urls.py", line 4, in <module>
    from Web.views.connection import connectionIndex, connectionDetail
  File "/opt/DionaeaFR/Web/views/connection.py", line 22, in <module>
    from Web.filters.connection import ConnectionFilter
  File "/opt/DionaeaFR/Web/filters/connection.py", line 1, in <module>
    import django_filters as filters
  File "/usr/local/lib/python2.7/dist-packages/django_filters/__init__.py", line 3, in <module>
    from .filterset import FilterSet
  File "/usr/local/lib/python2.7/dist-packages/django_filters/filterset.py", line 13, in <module>
    from django.db.models.fields.related import ForeignObjectRel
ImportError: cannot import name ForeignObjectRel

**Comment by iph0n3** [comment]
you can try django==1.8
pip install django==1.8
