### ISSUE TITLE
Unable to start server 

### ISSUE THREAD

**Issue by 25223015** [rubenespadas/DionaeaFR#40]
Hi I am unable to start the web server not sure if this is due to a new version of Django I get the following error:

Unhandled exception in thread started by <function wrapper at 0x7fd5816f7320>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/DionaeaFR/DionaeaFR/urls.py", line 1, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name patterns

**Comment by ksufer** [comment]
also in my server：

Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f63622a2140>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/DionaeaFR/DionaeaFR/urls.py", line 1, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name patterns

**Comment by ksufer** [comment]
ok i solved
vim /opt/DionaeaFR/DionaeaFR/urls.py

from django.conf.urls import url

from Web.views.other import home
from Web.views.connection import connectionIndex, connectionDetail
from Web.views.download import downloadIndex
from Web.views.graph import services, servicesData
from Web.views.graph import ports, portsData
from Web.views.graph import urls, urlsData
from Web.views.graph import malware, malwareData
from Web.views.graph import ips, ipsData, ipsCountries
from Web.views.graph import connections, connectionsData, connCountries
from Web.views.graph import timeline
from Web.views.map import attackersMap, countriesMap


urlpatterns = [

    url(
        r'^$',
        home
    ),
    url(
        r'^connections/$',
        connectionIndex,
        name='connection-index'
    ),
    url(
        r'^connections/(?P<connection_id>\d+)/',
        connectionDetail,
        name='connection-detail'
    ),
    url(
        r'^downloads/',
        downloadIndex,
        name='download-index'
    ),
    url(
        r'^graphs/services/$',
        services,
        name='services'
    ),
    url(
        r'^graphs/servicesdata/$',
        servicesData,
        name='services-data'
    ),
    url(
        r'^graphs/ports/$',
        ports,
        name='ports'
    ),
    url(
        r'^graphs/portsdata/$',
        portsData,
        name='ports-data'
    ),
    url(
        r'^graphs/urls/$',
        urls,
        name='urls'
    ),
    url(
        r'^graphs/urlsdata/$',
        urlsData,
        name='urls-data'
    ),
    url(
        r'^graphs/malware/$',
        malware,
        name='malware'
    ),
    url(
        r'^graphs/malwaredata/$',
        malwareData,
        name='malware-data'
    ),
    url(
        r'^graphs/ips/$',
        ips,
        name='ips'
    ),
    url(
        r'^graphs/ipsdata/$',
        ipsData,
        name='ips-data'
    ),
    url(
        r'^graphs/connections/$',
        connections,
        name='connections'
    ),
    url(
        r'^graphs/connectionsdata/$',
        connectionsData,
        name='connections-data'
    ),
    url(
        r'^graphs/timeline/$',
        timeline,
        name='timeline'
    ),
    url(
        r'^graphs/conncountries/$',
        connCountries,
        name='conn-countries'
    ),
    url(
        r'^graphs/ipscountries/$',
        ipsCountries,
        name='ips-countries'
    ),
    url(
        r'^maps/attackers/$',
        attackersMap,
        name='attackers-map'
    ),
    url(
        r'^maps/countries/$',
        countriesMap,
        name='countries-map'
    ),
]

# vim: set expandtab:ts=4

**Comment by Icchan92** [comment]
I tried both downgrading my django, which created other issues as django-tables2 requires a newer version of django and I  tried the code above, which gave another error: 

`root@ip-172-31-12-x:/opt/DionaeaFR# python manage.py runserver 0.0.0.0:8000
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f5c77c8a758>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/DionaeaFR/DionaeaFR/urls.py", line 5, in <module>
    from Web.views.download import downloadIndex
  File "/opt/DionaeaFR/Web/views/download.py", line 11, in <module>
    length = len(Download.objects.all())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
django.db.utils.OperationalError: no such table: downloads`

Any idea what the issue might be?
