### ISSUE TITLE
Installation successful, server does not work

### ISSUE THREAD

**Issue by jzone3** [rubenespadas/DionaeaFR#41]
Hi, I was successfully able to install DionaeaFR and its requirements. However, once I get to the step of running the 'manage.py runserver' and loading the page on a browser, the server errors:
```
Exception happened during processing of request from ('[IP_ADDR]', 56860)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
```

I have been unable to find anything helpful online about this error. Here are the versions of my system:
```
Ubuntu: 14.04 (DigitalOcean)
Python: 2.76
Django: 1.11.13 (I have tried multiple Django versions but none fix this)
django-tables2: 1.21.2
```

Any advice? Thanks!

**Comment by jzone3** [comment]
Okay, it looks like it works on port 80, but not the suggested 8000. Maybe `dionaea` is interfering with the use of 8000?
